kirby:
  url: https://github.com/getkirby/kirby.git
  tag-regex: '([0-9]+)\.([0-9]+)\.([0-9]+)'
  tag-exclude: '.*(?:rc|alpha|beta).*'
  current-file: kirby.php
  current-file-regex: '\$version\s*=\s*''([0-9]*)\.?([0-9]*)?\.?([0-9]*)?'';'
phpmyadmin:
  url: https://github.com/phpmyadmin/phpmyadmin.git
  tag-regex: 'RELEASE_([0-9]+)_([0-9]+)_([0-9]+)_?([0-9]+)?'
  tag-exclude: ".*(?:rc|alpha|beta).*"
  current-file: libraries/classes/Version.php
  current-file-regex: 'public\s*const\s*VERSION\s*=\s*''([0-9]*)\.?([0-9]*)\.?([0-9]*)?\.?([0-9]*)?-?(.*)?'''
baikal:
  url: https://github.com/fruux/Baikal.git
  tag-regex: '([0-9]+)\.([0-9]+)\.([0-9]+)'
  tag-exclude: '.*(?:rc|alpha|beta).*'
  current-file: Core/Distrib.php
  current-file-regex: 'define\("BAIKAL_VERSION",\s*"([0-9]*)\.?([0-9]*)?\.?([0-9]*)?"\);'
roundcube:
  url: https://github.com/roundcube/roundcubemail.git
  tag-regex: 'v?([0-9]+)\.([0-9]+)\.?([0-9]+)?'
  tag-exclude: '.*(?:rc|alpha|beta).*'
  current-file: program/include/iniset.php
  current-file-regex: 'define\(''RCMAIL_VERSION'',\s*''([0-9]*)\.?([0-9]*)?\.?([0-9]*)?-?(.*)?''\);'
nextcloud:
  url: https://github.com/nextcloud/server.git
  tag-regex: 'v([0-9]+)\.([0-9]+)\.?([0-9]+)?'
  tag-exclude: '.*(?:rc|alpha|beta).*'
  current-file: version.php
  current-file-regex: '\$OC_VersionString\s*=\s*''([0-9]*)\.?([0-9]*)?\.?([0-9]*)?\s?(.*)?'';'
modx:
  url: https://github.com/modxcms/revolution.git
  tag-regex: 'v([0-9]+)\.([0-9]+)\.([0-9]+)-pl([0-9]*)'
  tag-exclude: '.*(?:rc|alpha|beta).*'
  current-file: core/docs/version.inc.php
  current-file-regex: ['\$v\[''version''\]=\s*''([0-9]+)'';', '\$v\[''major_version''\]=\s*''([0-9]+)'';', '\$v\[''minor_version''\]=\s*''([0-9]+)'';']
wordpress:
  url: git://core.git.wordpress.org/
  tag-regex: '([0-9]+)\.?([0-9]+)?\.?([0-9]+)?'
  tag-exclude: '.*(?:rc|alpha|beta).*'
  current-file: wp-includes/version.php
  current-file-regex: '\$wp_version\s*=\s*''([0-9]*)\.?([0-9]*)?\.?([0-9]*)?-?(.*)?'';'
processwire:
  url: https://github.com/processwire/processwire.git
  tag-regex: '([0-9]+)\.([0-9]+)\.([0-9]+)'
  tag-exclude: '.*(?:rc|alpha|beta).*'
  current-file: wire/core/ProcessWire.php
  current-file-regex: ['const\s*versionMajor\s*=\s*([0-9]+);', 'const\s*versionMinor\s*=\s*([0-9]+);', 'const\s*versionRevision\s*=\s*([0-9]+);']
grav:
  url: https://github.com/getgrav/grav.git
  tag-regex: '([0-9]+)\.([0-9]+)\.([0-9]+)\.?([0-9]*)'
  tag-exclude: '.*(?:rc|alpha|beta).*'
  current-file: system/defines.php
  current-file-regex: 'define\(''GRAV_VERSION'',\s*''([0-9]*)\.?([0-9]*)?\.?([0-9]*)?\.?([0-9]*)?''\);'
limesurvey:
  url: https://github.com/LimeSurvey/LimeSurvey.git
  tag-regex: '([0-9]+)\.([0-9]+)\.([0-9]+)\+?([0-9]*)'
  tag-exclude: '.*(?:rc|alpha|beta).*'
  current-file: application/config/version.php
  current-file-regex: ['\$config\[''versionnumber''\]\s*=\s*''([0-9]*)\.?([0-9]*)?\.?([0-9]*)?'';', '\$config\[''buildnumber''\]\s*=\s*''([0-9]*)'';']
mediawiki:
  url: https://gerrit.wikimedia.org/r/p/mediawiki/core.git
  tag-regex: '([0-9]+)\.([0-9]+)\.([0-9]+)'
  tag-exclude: '.*(?:rc|alpha|beta).*'
  current-file: includes/Defines.php
  current-file-regex: 'define\(\s*''MW_VERSION'',\s*''([0-9]*)\.?([0-9]*)?\.?([0-9]*)?-?(.*)?''\s*\);'
matomo:
  url: https://github.com/matomo-org/matomo.git
  tag-regex: '([0-9]+)\.([0-9]+)\.([0-9]+)'
  tag-exclude: '.*(?:rc|alpha|beta|-b).*'
  current-file: core/Version.php
  current-file-regex: 'const\s*VERSION\s*=\s*''([0-9]*)\.?([0-9]*)\.?([0-9]*)?-?(.*)?'';'
sgwi:
  url: https://github.com/flok99/sgwi.git
  tag-regex: '([0-9]+)\.?([0-9]+)?\.?([0-9]+)?'
  tag-exclude: '.*(?:rc|alpha|beta|-b).*'
  current-file: index.php
  current-file-regex: 'Version:\s*([0-9]*)\.?([0-9]*)?\.?([0-9]*)?'
poweradmin:
  url: https://github.com/poweradmin/poweradmin.git
  tag-regex: 'v([0-9]+)\.?([0-9]+)?\.?([0-9]+)?'
  tag-exclude: '.*(?:rc|alpha|beta|-b).*'
  current-file: inc/version.inc.php # later: vendor/poweradmin/Version.php
  current-file-regex: '\$VERSION\s*=\s*''([0-9]*)\.?([0-9]*)?\.?([0-9]*)?'';' # later: 'const\s*VERSION\s*=\s*''([0-9]*)\.?([0-9]*)?\.?([0-9]*)?'';'
gitea:
  url: https://github.com/go-gitea/gitea.git
  tag-regex: 'v([0-9]+)\.?([0-9]+)?\.?([0-9]+)?'
  tag-exclude: '.*(?:rc|alpha|beta|-b|dev).*'
  current-command: 'gitea --version'
  current-command-regex: 'Gitea version \s*([0-9]*)\.?([0-9]*)?\.?([0-9]*)?'
  current-file: main.go
  current-file-regex: 'var Version = "([0-9]*)\.?([0-9]*)\.?([0-9]*)?-?(.*)?"'
lychee:
  url: https://github.com/LycheeOrg/Lychee.git
  tag-regex: 'v([0-9]+)\.?([0-9]+)?\.?([0-9]+)?'
  tag-exclude: '.*(?:-RC|-beta|-alpha).*'
  current-file: version.md
  current-file-regex: '([0-9]*)\.?([0-9]*)\.?([0-9]*)'