th-kirby:
  app: kirby
  path: test/kirby
phpmyadmin:
  app: phpmyadmin
  path: test/phpmyadmin
baikal:
  app: baikal
  path: test/Baikal
roundcube:
  app: roundcube
  path: test/roundcubemail
nextcloud:
  app: nextcloud
  path: test/server
dc-modx:
  app: modx
  path: test/revolution